    <div class="row">
    <div class="col-lg-12">
      <div class="box">
        <header>
          <div class="icons">
            <i class="fa fa-th-large"></i>
          </div>
          <h5>CKEditor</h5>

          <!-- .toolbar -->
          <div class="toolbar">
            <nav style="padding: 8px;">
              <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
                <i class="fa fa-minus"></i>
              </a> 
              <a href="javascript:;" class="btn btn-default btn-xs full-box">
                <i class="fa fa-expand"></i>
              </a> 
              <a href="javascript:;" class="btn btn-danger btn-xs close-box">
                <i class="fa fa-times"></i>
              </a> 
            </nav>
          </div><!-- /.toolbar -->
        </header>
        <div class="body">
          <form>
            <textarea id="ckeditor" class="ckeditor"></textarea>
            <div class="form-actions no-margin-bottom" id="cleditorForm">
              <input type="submit" value="Submit" class="btn btn-primary">
            </div>
          </form>
        </div>
      </div>
    </div><!-- /.col-lg-12 -->
    </div><!-- /.row -->
<script src="<?php echo $this->getStaticBasePath();?>/<?php echo $this->getStaticVersion();?>/manage/libs/ckeditor/ckeditor.js"></script>
